FROM centos:7

ENV RELEASE_BASE=https://packages.2600hz.com/centos/7/stable/2600hz-release
ENV RELEASE_VER=4.3
ENV META_PKG=2600hz-release-${RELEASE_VER}-0.el7.centos.noarch.rpm
ENV LATEST_RELEASE=${RELEASE_BASE}/${RELEASE_VER}/${META_PKG}
ENV HOME /opt/kazoo
ENV KAZOO_NODE kazoo-ecallmgr
ENV LOG_DIR /var/log/kazoo
ENV LOG_FILE ${LOG_DIR}/ecallmgr.log
ENV PID_FILE /var/run/kazoo/${KAZOO_NODE}.pid

RUN yum -y update && yum clean all
RUN yum -y install epel-release && yum clean all
RUN yum -y install wget curl net-tools

RUN echo "signalwire" > /etc/yum/vars/signalwireusername
RUN echo "pat_92HiXjNgtcBS3WXKwzRqwcPB" > /etc/yum/vars/signalwiretoken
RUN wget --http-user=$(cat /etc/yum/vars/signalwireusername) --http-password=$(cat /etc/yum/vars/signalwiretoken) https://freeswitch.signalwire.com/repo/yum/centos_release/freeswitch-release-repo-0-1.noarch.rpm
RUN yum install -y ${LATEST_RELEASE} --skip-broken
RUN rpm -i --replacefiles freeswitch-release-repo-0-1.noarch.rpm

RUN yum install -y kazoo-core

RUN rm -rf ${LOG_DIR} && \
    mkdir -p ${LOG_DIR} /tmp/erl_pipes/${KAZOO_NODE} /var/run/kazoo && \
    touch ${LOG_FILE} && \
    chmod -R 755 ${LOG_DIR} /tmp/erl_pipes/${KAZOO_NODE} /var/run/kazoo && \
    rm -f ${PID_FILE}

COPY kazoo_start_script.sh /usr/local/bin/kazoo_start_script.sh
RUN chmod +x /usr/local/bin/kazoo_start_script.sh

CMD ["/usr/local/bin/kazoo_start_script.sh", "start"]
