version: '3.3'
services:

  freeswitch:
    platform: linux/amd64
    hostname: freeswitch
    build:
      context: ./freeswitch
      dockerfile: DockerFile
    networks:
      lan:
        ipv4_address: 10.10.1.2


  rabbitmq:
    platform: linux/amd64
    hostname: rabbitmq
    build:
        context: ./rabbitmq
        dockerfile: DockerFile
    networks:
        lan:
            ipv4_address: 10.10.1.3

  kamailio:
    platform: linux/amd64
    hostname: kamailio
    build:
      context: ./kamailio
      dockerfile: DockerFile
    networks:
      lan:
        ipv4_address: 10.10.1.4

  couchdb:
    platform: linux/amd64
    image: couchdb:2.3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      lan:
        ipv4_address: 10.10.1.5

  haproxy:
    platform: linux/amd64
    hostname: haproxy
    build:
      context: ./haproxy
      dockerfile: DockerFile
    networks:
        lan:
            ipv4_address: 10.10.1.6

  kazoo-applications:
    platform: linux/amd64
    hostname: kazoo-applications
    build:
      context: ./kazoo-applications
      dockerfile: DockerFile
    networks:
        lan:
            ipv4_address: 10.10.1.7

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24