FROM centos:7
# Update the system and install basic utilities
ENV RELEASE_BASE=https://packages.2600hz.com/centos/7/stable/2600hz-release
ENV RELEASE_VER=4.3
ENV META_PKG=2600hz-release-${RELEASE_VER}-0.el7.centos.noarch.rpm
ENV LATEST_RELEASE=${RELEASE_BASE}/${RELEASE_VER}/${META_PKG}

RUN yum -y update && yum clean all
RUN yum -y install epel-release && yum clean all
RUN yum -y install wget curl net-tools wget vim
RUN wget https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
RUN rpm -Uvh erlang-solutions-1.0-1.noarch.rpm

RUN echo "signalwire" > /etc/yum/vars/signalwireusername
RUN echo "pat_92HiXjNgtcBS3WXKwzRqwcPB" > /etc/yum/vars/signalwiretoken

RUN wget --http-user=$(cat /etc/yum/vars/signalwireusername) --http-password=$(cat /etc/yum/vars/signalwiretoken) https://freeswitch.signalwire.com/repo/yum/centos_release/freeswitch-release-repo-0-1.noarch.rpm
RUN yum install -y ${LATEST_RELEASE} --skip-broken
RUN rpm -i --replacefiles freeswitch-release-repo-0-1.noarch.rpm
RUN yum install -y erlang
RUN yum install -y kazoo-rabbitmq \

# This is based on the prepare() function that ships with the kazoo-rabbitmq package
ENV RABBITMQ_USER=rabbitmq \
    RABBITMQ_BIN=/usr/lib/rabbitmq/bin/rabbitmq-server \
    RABBITMQ_PID=/var/run/rabbitmq/kazoo-rabbitmq.pid \
    RABBITMQ_ENV=/etc/kazoo/rabbitmq/rabbitmq-env.conf \
    RABBITMQ_HOME=/var/lib/rabbitmq \
    RABBITMQ_CONFIG_FILE=/etc/kazoo/rabbitmq/rabbitmq \
    RABBITMQ_ENABLED_PLUGINS_FILE=/etc/kazoo/rabbitmq/enabled_plugins \
    RABBITMQ_NODENAME=kazoo-rabbitmq

RUN rm -rf /var/lib/rabbitmq/mnesia/kazoo-rabbit* && \
    mkdir -p ${RABBITMQ_HOME} && \
    chown -R ${RABBITMQ_USER} ${RABBITMQ_HOME} && \
    mkdir -p /var/log/rabbitmq && \
    chown -R ${RABBITMQ_USER} /var/log/rabbitmq && \
    mkdir -p /var/run/rabbitmq && \
    chown -R ${RABBITMQ_USER} /var/run/rabbitmq && \
    if [ -e ${RABBITMQ_PID} ]; then \
        rm -rf ${RABBITMQ_PID}; \
    fi

COPY rabbitmq-env.conf ${RABBITMQ_ENV}

CMD["rabbitmq-server"]