FROM centos:7
# Update the system and install basic utilities
ENV RELEASE_BASE=https://packages.2600hz.com/centos/7/stable/2600hz-release
ENV RELEASE_VER=4.3
ENV META_PKG=2600hz-release-${RELEASE_VER}-0.el7.centos.noarch.rpm
ENV LATEST_RELEASE=${RELEASE_BASE}/${RELEASE_VER}/${META_PKG}

RUN yum -y update && yum clean all
RUN yum -y install epel-release && yum clean all
RUN yum -y install wget curl net-tools wget vim

RUN echo "[2600hz-stable]" > /etc/yum.repos.d/2600hz-stable.repo
RUN echo "name=2600Hz Stable Repo" >> /etc/yum.repos.d/2600hz-stable.repo
RUN echo "baseurl=https://packages.2600hz.com/centos/\$releasever/stable" >> /etc/yum.repos.d/2600hz-stable.repo
RUN echo "enabled=1" >> /etc/yum.repos.d/2600hz-stable.repo
RUN echo "gpgcheck=0" >> /etc/yum.repos.d/2600hz-stable.repo
RUN echo "sslverify=false" >> /etc/yum.repos.d/2600hz-stable.repo



RUN echo "signalwire" > /etc/yum/vars/signalwireusername
RUN echo "pat_92HiXjNgtcBS3WXKwzRqwcPB" > /etc/yum/vars/signalwiretoken

RUN wget --http-user=$(cat /etc/yum/vars/signalwireusername) --http-password=$(cat /etc/yum/vars/signalwiretoken) https://freeswitch.signalwire.com/repo/yum/centos_release/freeswitch-release-repo-0-1.noarch.rpm
RUN yum install -y ${LATEST_RELEASE} --skip-broken
RUN rpm -i --replacefiles freeswitch-release-repo-0-1.noarch.rpm

RUN yum remove erlang erlang-* -y
RUN wget https://github.com/rabbitmq/erlang-rpm/releases/download/v20.3.8.15/erlang-20.3.8.15-1.el7.centos.x86_64.rpm
RUN yum install -y erlang-20.3.8.15-1.el7.centos.x86_64.rpm

RUN yum install -y kazoo-rabbitmq

RUN chown -R rabbitmq:rabbitmq /var/lib/rabbitmq

# This is based on the prepare() function that ships with the kazoo-rabbitmq package
ENV RABBITMQ_USER=rabbitmq \
    RABBITMQ_BIN=/usr/lib/rabbitmq/bin/rabbitmq-server \
    RABBITMQ_PID=/var/run/rabbitmq/kazoo-rabbitmq.pid \
    RABBITMQ_ENV=/etc/kazoo/rabbitmq/rabbitmq-env.conf \
    RABBITMQ_HOME=/var/lib/rabbitmq \
    RABBITMQ_CONFIG_FILE=/etc/kazoo/rabbitmq/rabbitmq \
    RABBITMQ_ENABLED_PLUGINS_FILE=/etc/kazoo/rabbitmq/enabled_plugins \
    RABBITMQ_NODENAME=kazoo-rabbitmq

# Prepare RabbitMQ Directories and Permissions
RUN mkdir -p ${RABBITMQ_HOME} /var/log/rabbitmq /var/run/rabbitmq && \
    chown -R ${RABBITMQ_USER}:${RABBITMQ_USER} ${RABBITMQ_HOME} /var/log/rabbitmq /var/run/rabbitmq && \
    rm -rf /var/lib/rabbitmq/mnesia/kazoo-rabbit* && \
    if [ -e ${RABBITMQ_PID} ]; then rm -rf ${RABBITMQ_PID}; fi

COPY rabbitmq-env.conf ${RABBITMQ_ENV}

COPY start-rabbitmq.sh .
RUN chmod +x start-rabbitmq.sh


CMD ["./start-rabbitmq.sh"]
#CMD ["tail", "-f", "/dev/null"]